/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : KBI3.H
**     Project   : DEMO4
**     Processor : MC9S08LC60PU
**     Beantype  : Init_KBI
**     Version   : Bean 01.020, Driver 01.07, CPU db: 2.87.237
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 1/15/2009, 1:28 AM
**     Abstract  :
**          This file implements the KBI (KBI1) module initialization
**          according to the Peripheral Initialization Bean settings, and defines
**          interrupt service routines prototypes.
**          The KBI module is the serial peripheral interface module,which allows 
**          full-duplex, synchronous, serial communications with peripheral devices.
**          The keyboard interrupt module (KBI) provides a few independently maskable 
**          external interrupts. When a port pin is enabled for keyboard interrupt 
**          function, an internal pullup/pulldown device is also enabled on the pin.

**     Settings  :
**          Bean name                                      : KBI3
**          Device                                         : KBI1
**          Settings 
**            Triggering sensitivity                       : edge
**          Pins 
**            Pin0                                         : Enabled
**              Pin                                        : PTA0_KBI1P0_AD0
**              Pin signal                                 : 
**            Pin1                                         : Enabled
**              Pin                                        : PTA1_KBI1P1_AD1
**              Pin signal                                 : 
**            Pin2                                         : Enabled
**              Pin                                        : PTA2_KBI1P2_AD2_ACMPPLUS
**              Pin signal                                 : 
**            Pin3                                         : Enabled
**              Pin                                        : PTA3_KBI1P3_AD3_ACMPMINUS
**              Pin signal                                 : 
**            Pin4                                         : Enabled
**              Pin                                        : PTA4_KBI1P4_AD4
**              Pin signal                                 : 
**            Pin5                                         : Enabled
**              Pin                                        : PTA5_KBI1P5_AD5
**              Pin signal                                 : 
**            Pin6                                         : Enabled
**              Pin                                        : PTA6_KBI1P6_AD6
**              Pin signal                                 : 
**            Pin7                                         : Enabled
**              Pin                                        : PTA7_KBI1P7_AD7
**              Pin signal                                 : 
**          Interrupts 
**            Keyboard request 
**              Interrupt                                  : Vkeyboard1
**              Keyboard request interrupt                 : Disabled
**              ISR name                                   : 
**          Initialization 
**            Call Init method                             : yes
**     Contents  :
**         Init - void KBI3_Init(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2006
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __KBI3
#define __KBI3

/* MODULE KBI3. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "Cpu.h"


void KBI3_Init(void);
/*
** ===================================================================
**     Method      :  KBI3_Init (bean Init_KBI)
**
**     Description :
**         This method initializes registers of the KBI module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END KBI3. */

#endif
/* ifndef __KBI3 */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.01 [03.92]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
