/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Vectors.C
**     Project   : DEMO4
**     Processor : MC9S08LC60PU
**     Version   : Bean 01.058, Driver 01.29, CPU db: 2.87.237
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 1/15/2009, 1:28 AM
**     Abstract  :
**         This bean "MC9S08LC60_80" contains initialization of the
**         CPU and provides basic methods and events for CPU core
**         settings.
**     Settings  :
**
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2006
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/


#include "Cpu.h"
#include "KBI3.h"
extern near void _EntryPoint(void);

void (* near const _vect[])() @0xFFD2 = { /* Interrupt vector table */
         Cpu_Interrupt,                /* Int.no. 22 Vlcd (at FFD2)                  Unassigned */
         Cpu_Interrupt,                /* Int.no. 21 Vrti (at FFD4)                  Unassigned */
         Cpu_Interrupt,                /* Int.no. 20 Viic (at FFD6)                  Unassigned */
         Cpu_Interrupt,                /* Int.no. 19 Vacmp (at FFD8)                 Unassigned */
         Cpu_Interrupt,                /* Int.no. 18 Vadc (at FFDA)                  Unassigned */
         Cpu_Interrupt,                /* Int.no. 17 Vkeyboard2 (at FFDC)            Unassigned */
         Cpu_Interrupt,                /* Int.no. 16 Vkeyboard1 (at FFDE)            Unassigned */
         Cpu_Interrupt,                /* Int.no. 15 Vscitx (at FFE0)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 14 Vscirx (at FFE2)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 13 Vscierr (at FFE4)               Unassigned */
         Cpu_Interrupt,                /* Int.no. 12 Vspi2 (at FFE6)                 Unassigned */
         Cpu_Interrupt,                /* Int.no. 11 Vspi1 (at FFE8)                 Unassigned */
         Cpu_Interrupt,                /* Int.no. 10 Vtpm2ovf (at FFEA)              Unassigned */
         Cpu_Interrupt,                /* Int.no.  9 Vtpm2ch1 (at FFEC)              Unassigned */
         Cpu_Interrupt,                /* Int.no.  8 Vtpm2ch0 (at FFEE)              Unassigned */
         Cpu_Interrupt,                /* Int.no.  7 Vtpm1ovf (at FFF0)              Unassigned */
         Cpu_Interrupt,                /* Int.no.  6 Vtpm1ch1 (at FFF2)              Unassigned */
         Cpu_Interrupt,                /* Int.no.  5 Vtpm1ch0 (at FFF4)              Unassigned */
         Cpu_VicgInterrupt,            /* Int.no.  4 Vicg (at FFF6)                  Used */
         Cpu_Interrupt,                /* Int.no.  3 Vlvd (at FFF8)                  Unassigned */
         Cpu_Interrupt,                /* Int.no.  2 Virq (at FFFA)                  Unassigned */
         Cpu_Interrupt,                /* Int.no.  1 Vswi (at FFFC)                  Unassigned */
         _EntryPoint                   /* Int.no.  0 Vreset (at FFFE)                Reset vector */
};

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.01 [03.92]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
